Fix compilation error due to unused variable when KANSHI_HAS_VARLINK isn't truthy
The error:

    ../main.c:623:13: error: variable ‘listen_fd’ set but not used [-Werror=unused-but-set-variable]